#!/usr/bin/env python3
"""Generate Sorrow's spoken announcements as embedded PCM.

The module has no screen, and the LED is already busy marking the bar - a second
signal competing with it is hard to read, which is what happened to the button
and the bank code. Speech puts state changes on a channel that is not contested.

macOS `say` plus ffmpeg. 11025 Hz, 8-bit unsigned: about 15 KB a phrase, which
is nothing against the SRAM budget, and the telephone quality suits the job.

Run from daisy_grids/:  python3 tools/speech/make_speech.py
"""
import subprocess, pathlib, sys

VOICE = "Daniel"
RATE  = 11025

PHRASES = [
    ("kSpeechBankOriginal", "Original patterns"),
    ("kSpeechBankClub",     "Club patterns"),
    ("kSpeechBankTrad",     "Traditional patterns"),
    ("kSpeechBankLatin",    "Latin patterns"),
    ("kSpeechBankUser",     "User patterns"),
]

OUT_CPP = pathlib.Path("src/speech_data.cpp")
OUT_H   = pathlib.Path("include/speech_data.h")
TMP     = pathlib.Path("/tmp/sorrow_speech")


def render(text):
    TMP.mkdir(exist_ok=True)
    aiff, raw = TMP / "s.aiff", TMP / "s.raw"
    subprocess.run(["say", "-v", VOICE, "-o", str(aiff), text], check=True)
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(aiff),
                    "-ac", "1", "-ar", str(RATE), "-f", "u8", str(raw)], check=True)
    return raw.read_bytes()


def main():
    cpp = ["// Auto-generated file. Do not edit by hand.",
           "//",
           "// Spoken announcements, generated by tools/speech/make_speech.py.",
           f"// macOS `say` voice \"{VOICE}\", {RATE} Hz, 8-bit unsigned PCM.",
           "//",
           "// SPDX-License-Identifier: GPL-3.0-or-later",
           "",
           '#include "speech_data.h"',
           "",
           "namespace sorrow {",
           ""]
    hdr = ["// Declarations for the generated speech in src/speech_data.cpp.",
           "//",
           "// SPDX-License-Identifier: GPL-3.0-or-later",
           "",
           "#pragma once",
           "",
           "#include <cstddef>",
           "#include <cstdint>",
           "",
           "namespace sorrow {",
           "",
           f"constexpr float kSpeechRateHz = {RATE}.0f;",
           ""]
    for name, text in PHRASES:
        pcm = render(text)
        print(f'  "{text}" -> {len(pcm)} bytes ({len(pcm)/RATE:.2f}s)')
        cpp.append(f"// \"{text}\"")
        cpp.append(f"const uint8_t {name}[{len(pcm)}] = {{")
        for i in range(0, len(pcm), 20):
            cpp.append("    " + ", ".join(str(b) for b in pcm[i:i+20]) + ",")
        cpp.append("};")
        cpp.append("")
        hdr.append(f"// \"{text}\"")
        hdr.append(f"extern const uint8_t {name}[{len(pcm)}];")
        hdr.append(f"constexpr size_t {name}Len = {len(pcm)};")
        hdr.append("")
    cpp += ["} // namespace sorrow", ""]
    hdr += ["} // namespace sorrow", ""]
    OUT_CPP.write_text("\n".join(cpp))
    OUT_H.write_text("\n".join(hdr))
    print(f"wrote {OUT_CPP} ({OUT_CPP.stat().st_size} bytes) and {OUT_H}")


if __name__ == "__main__":
    main()
