// GENERATED by tools/notamp_design.py — do not edit by hand; rerun it.
// The twelve not-amps (2026-10-02): a starter capture with one transform and one
// steer, each measured outside the amp region by two judges and approved by ear.
// Types and processing: notamp_dsp.h. gain_db is the inverse of the measured level,
// so the steer changes the sound rather than the volume.
#pragma once

#include "notamp_dsp.h"

namespace notamps
{
constexpr Def kDefs[] = {
    {"SINE PLX", Kind::Sine, "PLEXI LORE", nullptr, "PLEXI LORE", 0.3f, 8.0f, true, 0, 0.0f,
     {20.88f, 25.72f, 28.80f, 28.26f, 28.38f, 29.25f, 29.99f, 29.47f, 29.73f}},
    {"SINE BUG", Kind::Sine, "BUGERA G5", nullptr, "BUGERA G5", 0.3f, 8.0f, true, 0, 0.0f,
     {16.40f, 17.82f, 17.86f, 21.21f, 24.89f, 26.76f, 30.49f, 31.94f, 35.13f}},
    {"LINEAR TR", Kind::Slope, "TWO ROCK", nullptr, "TWO ROCK", 0.01f, 1.0f, false, 0, 0.0f,
     {0.00f, 0.72f, 1.48f, -0.60f, -5.41f, -9.98f, -14.04f, -17.61f, -20.85f}},
    {"RECT ORG", Kind::Slope, "ORANGE TH", nullptr, "ORANGE TH", 0.01f, -1.0f, false, 0, 0.0f,
     {-0.00f, 2.73f, 4.64f, 2.95f, -0.19f, -3.61f, -6.54f, -9.13f, -10.68f}},
    {"FB100 F57", Kind::FbGain, "FENDER 57", nullptr, "FENDER 57", 0.0f, 0.95f, false, 0, 480.0f,
     {-0.00f, -0.98f, -0.87f, -0.90f, -0.98f, -1.11f, -1.22f, -1.27f, -1.36f}},
    {"FB PCH PLX", Kind::FbPitch, "PLEXI LORE", nullptr, "PLEXI LORE", 48.0f, 1200.0f, true, 0, 0.8f,
     {-0.73f, -0.32f, -0.28f, -0.17f, -0.09f, -0.34f, -0.22f, -0.26f, -0.25f}},
    {"FRZ E TR", Kind::Freeze, "TWO ROCK", nullptr, "TWO ROCK", 1.0f, 1024.0f, true, 3, 0.0f,
     {-0.00f, -0.00f, -0.00f, -0.02f, -0.03f, 0.13f, 1.23f, 8.11f, 7.35f}},
    {"FRZ M F57", Kind::Freeze, "FENDER 57", nullptr, "FENDER 57", 1.0f, 1024.0f, true, 11, 0.0f,
     {-0.00f, 0.00f, -0.01f, -0.04f, -0.05f, 0.02f, 0.20f, 4.85f, 5.94f}},
    {"FRZ M KAY", Kind::Freeze, "KAY 703", nullptr, "KAY 703", 1.0f, 1024.0f, true, 11, 0.0f,
     {-0.00f, -0.00f, -0.04f, 0.00f, -0.21f, -0.15f, 0.65f, 7.71f, 8.34f}},
    {"FOLD ORG", Kind::Fold, "ORANGE TH", nullptr, "ORANGE TH", 1.0f, 0.05f, true, 11, 0.0f,
     {23.95f, 24.02f, 24.04f, 24.01f, 24.02f, 24.05f, 24.02f, 24.02f, 24.02f}},
    {"RATE SVT", Kind::Rate, "SVT-2 PRO", nullptr, "SVT-2 PRO", 1.0f, 6.0f, false, 0, 0.0f,
     {-0.00f, 3.05f, 3.05f, 2.52f, 2.52f, 1.52f, 1.52f, 3.18f, 3.18f}},
    {"PAST BLU", Kind::Morph, "BUGERA G5", "BLUESBRKR", "BLUESBRKR", 1.0f, 1.3f, false, 0, 0.0f,
     {0.00f, -1.91f, -3.60f, -5.17f, -7.29f, -10.56f, -14.96f, -19.52f, -23.96f}},
};
constexpr int kCount = (int)(sizeof(kDefs) / sizeof(kDefs[0]));
} // namespace notamps
