// GENERATED by tools/notamp_design.py — do not edit by hand; rerun it.
// The twelve not-amps (2026-10-02): a starter capture with one transform and one
// steer, each measured outside the amp region by two judges and approved by ear.
// Types and processing: notamp_dsp.h. gain_db is the inverse of the measured level,
// so the steer changes the sound rather than the volume.
#pragma once

#include "notamp_dsp.h"

namespace notamps
{
constexpr Def kDefs[] = {
    {"SINE BUG", Kind::Sine, "BUGERA G5", nullptr, "BUGERA G5", 0.3f, 8.0f, true, 0, 0.0f,
     {17.14f, 21.79f, 21.92f, 21.52f, 24.90f, 27.40f, 30.83f, 33.66f, 39.37f}},
    {"LINEAR TR", Kind::Slope, "TWO ROCK", nullptr, "TWO ROCK", 0.01f, 1.0f, false, 0, 0.0f,
     {0.00f, 0.92f, 3.10f, 9.69f, 16.23f, 25.64f, 23.58f, 21.02f, 17.22f}},
    {"LINEAR TRY", Kind::Slope, "TRAYNOR", nullptr, "TRAYNOR", 0.01f, 1.0f, false, 0, 0.0f,
     {0.00f, 1.69f, 4.65f, 9.01f, 14.18f, 18.93f, 18.52f, 15.06f, 11.40f}},
    {"RECT ORG", Kind::Slope, "ORANGE TH", nullptr, "ORANGE TH", 0.01f, -1.0f, false, 0, 0.0f,
     {-0.00f, 2.75f, 5.71f, 9.76f, 9.14f, 3.75f, -0.54f, -3.08f, -5.37f}},
    {"FB100 F57", Kind::FbGain, "FENDER 57", nullptr, "FENDER 57", 0.0f, 0.95f, false, 0, 480.0f,
     {-0.00f, -1.04f, -0.94f, -1.00f, -1.08f, -1.22f, -1.34f, -1.35f, -1.42f}},
    {"FRZ E TR", Kind::Freeze, "TWO ROCK", nullptr, "TWO ROCK", 1.0f, 1024.0f, true, 3, 0.0f,
     {-0.00f, -0.00f, -0.00f, -0.02f, -0.02f, 0.15f, 1.35f, 8.41f, 7.47f}},
    {"FRZ M F57", Kind::Freeze, "FENDER 57", nullptr, "FENDER 57", 1.0f, 1024.0f, true, 11, 0.0f,
     {-0.00f, 0.00f, -0.01f, -0.04f, -0.05f, 0.05f, 0.41f, 5.88f, 7.76f}},
    {"FRZ M KAY", Kind::Freeze, "KAY 703", nullptr, "KAY 703", 1.0f, 1024.0f, true, 11, 0.0f,
     {-0.00f, -0.00f, -0.03f, 0.01f, -0.20f, -0.14f, 0.71f, 7.84f, 8.84f}},
    {"FOLD ORG", Kind::Fold, "ORANGE TH", nullptr, "ORANGE TH", 1.0f, 0.05f, true, 11, 0.0f,
     {28.61f, 28.75f, 28.82f, 28.87f, 28.88f, 28.89f, 28.89f, 28.89f, 28.88f}},
    {"RATE SVT", Kind::Rate, "SVT-2 PRO", nullptr, "SVT-2 PRO", 1.0f, 6.0f, false, 0, 0.0f,
     {-0.00f, 2.99f, 2.99f, 2.39f, 2.39f, 1.56f, 1.56f, 3.15f, 3.15f}},
    {"PAST BLU", Kind::Morph, "BUGERA G5", "BLUESBRKR", "BLUESBRKR", 1.0f, 1.3f, false, 0, 0.0f,
     {0.00f, -1.90f, -3.52f, -4.72f, -5.40f, -5.44f, -4.86f, -4.43f, -4.35f}},
    {"PAST PLX", Kind::Morph, "SVT-2 PRO", "PLEXI LORE", "PLEXI LORE", 1.0f, 1.3f, false, 0, 0.0f,
     {0.00f, -0.27f, 1.33f, 3.42f, 0.82f, -3.03f, -8.21f, -16.10f, -26.68f}},
};
constexpr int kCount = (int)(sizeof(kDefs) / sizeof(kDefs[0]));
} // namespace notamps
