// SPDX-License-Identifier: MIT
// Copyright (c) 2026 David Baghurst
//
// chaos_core pitch map — how steady is an algorithm's pitch? Host build, no hardware.
//
// periodmap.cpp asks whether a point is periodic. This asks the question TAME needs
// answered (docs/SECRET.md, section 2): what is the attractor's natural rotation
// frequency at each point on the CHAOS x CHAR plane, and how much does it jitter?
//
//   f_nat   upward zero crossings of X (DC removed) per unit of SIMULATED time.
//           Pitch in Hz is f_nat x simRate, so simRate = f_target / f_nat is the
//           scale-compensation table for coherent systems.
//   jitter  coefficient of variation of the crossing intervals. ~0 is periodic;
//           Rossler-type spirals stay near 0.1-0.2 even when fully chaotic (a pitch
//           with roughness); ~0.3 and above has no usable pitch.
//
// First measurement at mid CHAR (2026-09-30): Rossler f_nat 0.175-0.179 across the
// whole CHAOS range (+-1.2%), Van der Pol periodic but drifting 1.35 octaves with mu,
// Duffing locked to its drive (omega/2pi, or /3 and /5 in subharmonic windows),
// Lorenz and Chua erratic outside their periodic windows.
//
// Build:
//   g++ -O2 -std=c++17 -I common/chaos_core/include
//       common/chaos_core/tools/pitchmap.cpp common/chaos_core/src/Registry.cpp
//       -o /tmp/pitchmap && /tmp/pitchmap 0
//   (one line; split here for readability)
//
// Args: <algo index> [chaosMin chaosMax charMin charMax]
//   Output: two grids, f_nat then jitter. '!' = no oscillation (fixed point or
//   non-finite). Integrates at stableDt/2, so the figures are the ODE's, not RK4's.
//
//   pitchmap --emit > common/chaos_core/include/chaos_core/PitchTables.h
//   Measures every algorithm over its declared range on a finer grid and writes
//   the tables Voice::setPitch() reads. Cells with no oscillation take the value
//   of the nearest cell that has one. Regenerate after changing any algorithm or
//   range: the tables are only as good as the match between them and the code.

#include "chaos_core/Registry.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

using namespace chaos_core;

namespace {

constexpr int  kRows = 13, kCols = 7;
constexpr long kWarm = 100000, kRun = 400000;
constexpr size_t kMinCrossings = 10;

struct Pitch { bool ok; float fNat, jitter, xMean, xStd; };

Pitch measure(ChaosBase* a, float chaos, float charV) {
    const float dt = a->stableDt(chaos, charV) * 0.5f;
    a->init();
    a->setParams(chaos, dt, charV);
    double dc = 0.0, sq = 0.0;
    for (long i = 0; i < kWarm; i++) {
        a->stepSample();
        const float x = a->getX();
        if (!std::isfinite(x)) return {false, 0, 0, 0, 0};
        dc += x; sq += (double)x * x;
    }
    dc /= (double)kWarm;
    const double var = sq / (double)kWarm - dc * dc;
    const float xStd = (float)std::sqrt(var > 0.0 ? var : 0.0);

    std::vector<double> iv;
    double t = 0.0, lastT = -1.0;
    float prev = a->getX() - (float)dc;
    for (long i = 0; i < kRun; i++) {
        a->stepSample();
        t += dt;
        const float x = a->getX() - (float)dc;
        if (!std::isfinite(x)) return {false, 0, 0, 0, 0};
        if (prev < 0.0f && x >= 0.0f) {
            if (lastT >= 0.0) iv.push_back(t - lastT);
            lastT = t;
        }
        prev = x;
    }
    if (iv.size() < kMinCrossings) return {false, 0, 0, (float)dc, xStd};

    double m = 0.0;
    for (double v : iv) m += v;
    m /= (double)iv.size();
    double s = 0.0;
    for (double v : iv) s += (v - m) * (v - m);
    s = std::sqrt(s / (double)iv.size());
    return {true, (float)(1.0 / m), (float)(s / m), (float)dc, xStd};
}

float lerp(float a, float b, int i, int n) {
    return (n <= 1) ? a : a + (b - a) * (float)i / (float)(n - 1);
}

constexpr int kEmitRows = 17, kEmitCols = 9;

// Write PitchTables.h for every algorithm in the registry.
int emit() {
    std::printf("#pragma once\n");
    std::printf("// GENERATED by tools/pitchmap.cpp --emit. Do not hand-edit: regenerate, so the\n");
    std::printf("// tables and the attractors they describe stay the same code.\n");
    std::printf("//\n");
    std::printf("// f: natural rotation frequency (upward crossings of X) in cycles per unit of\n");
    std::printf("// simulated time, over each algorithm's declared CHAOS x CHAR range.\n");
    std::printf("// refCentre / refAmp: mean of X, and sqrt(2) x its standard deviation.\n\n");
    std::printf("#include \"chaos_core/ChaosBase.h\"\n\nnamespace chaos_core {\n");
    for (int ai = 0; ai < N_ALGOS; ai++) {
        ChaosBase* a = algos[ai];
        char id[32]; int n = 0;
        for (const char* c = a->name; *c && n < 31; c++) id[n++] = (*c == ' ') ? '_' : *c;
        id[n] = 0;

        static Pitch g[kEmitRows][kEmitCols];
        double cSum = 0.0, aSum = 0.0; int nOk = 0, nRef = 0;
        for (int i = 0; i < kEmitRows; i++)
            for (int j = 0; j < kEmitCols; j++) {
                g[i][j] = measure(a, lerp(a->chaosMin, a->chaosMax, i, kEmitRows),
                                     lerp(a->charMin, a->charMax, j, kEmitCols));
                if (g[i][j].ok) nOk++;
                if (g[i][j].xStd > 0.0f) { cSum += g[i][j].xMean; aSum += g[i][j].xStd; nRef++; }
            }
        const float refCentre = nRef ? (float)(cSum / nRef) : 0.0f;
        const float refAmp    = nRef ? (float)(1.41421356 * aSum / nRef) : 1.0f;

        std::printf("\n// %s: %d of %d cells oscillate; the rest take their nearest neighbour.\n",
                    a->name, nOk, kEmitRows * kEmitCols);
        std::printf("static const float kPitchF_%s[%d * %d] = {\n", id, kEmitRows, kEmitCols);
        for (int i = 0; i < kEmitRows; i++) {
            std::printf("   ");
            for (int j = 0; j < kEmitCols; j++) {
                float f = g[i][j].fNat;
                if (!g[i][j].ok) {
                    int best = 1 << 30;
                    for (int p = 0; p < kEmitRows; p++)
                        for (int q = 0; q < kEmitCols; q++) {
                            if (!g[p][q].ok) continue;
                            const int d = (p - i) * (p - i) + (q - j) * (q - j);
                            if (d < best) { best = d; f = g[p][q].fNat; }
                        }
                    if (best == (1 << 30)) f = a->fNatDefault;
                }
                std::printf(" %.6ff,", f);
            }
            std::printf("\n");
        }
        std::printf("};\n");
        std::printf("static const PitchGrid kPitchGrid_%s = {\n    %d, %d, %.6ff, %.6ff, %.6ff, %.6ff,\n"
                    "    kPitchF_%s, %.6ff, %.6ff\n};\n",
                    id, kEmitRows, kEmitCols, a->chaosMin, a->chaosMax, a->charMin, a->charMax,
                    id, refCentre, refAmp);
    }
    std::printf("\n}  // namespace chaos_core\n");
    return 0;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc > 1 && std::strcmp(argv[1], "--emit") == 0) return emit();
    const int idx = (argc > 1) ? std::atoi(argv[1]) : 0;
    if (idx < 0 || idx >= N_ALGOS) {
        std::printf("usage: pitchmap <0..%d> [chaosMin chaosMax charMin charMax]\n", N_ALGOS - 1);
        for (int i = 0; i < N_ALGOS; i++) std::printf("  %d  %s\n", i, algos[i]->name);
        return 1;
    }
    ChaosBase* a = algos[idx];
    const float cLo = (argc > 2) ? (float)std::atof(argv[2]) : a->chaosMin;
    const float cHi = (argc > 3) ? (float)std::atof(argv[3]) : a->chaosMax;
    const float hLo = (argc > 4) ? (float)std::atof(argv[4]) : a->charMin;
    const float hHi = (argc > 5) ? (float)std::atof(argv[5]) : a->charMax;

    static Pitch grid[kRows][kCols];
    for (int i = 0; i < kRows; i++)
        for (int j = 0; j < kCols; j++)
            grid[i][j] = measure(a, lerp(cLo, cHi, i, kRows), lerp(hLo, hHi, j, kCols));

    std::printf("%s — natural frequency per unit simulated time, and jitter\n", a->name);
    std::printf("CHAOS (%s) %g..%g down, CHAR (%s) %g..%g across%s\n",
                a->chaosLabel, cLo, cHi, a->charLabel, hLo, hHi,
                (argc > 2) ? "  [range overridden]" : "  [declared range]");

    for (int pass = 0; pass < 2; pass++) {
        std::printf("\n%s\n  %7s ", pass == 0 ? "f_nat" : "jitter (CV of period)", "chaos");
        for (int j = 0; j < kCols; j++) std::printf("%8.3g", lerp(hLo, hHi, j, kCols));
        std::printf("\n");
        for (int i = 0; i < kRows; i++) {
            std::printf("  %7.3g ", lerp(cLo, cHi, i, kRows));
            for (int j = 0; j < kCols; j++) {
                const Pitch& p = grid[i][j];
                if (!p.ok) std::printf("%8s", "!");
                else       std::printf("%8.4f", pass == 0 ? p.fNat : p.jitter);
            }
            std::printf("\n");
        }
    }

    float lo = 1e30f, hi = 0.0f;
    int coherent = 0, total = 0;
    for (int i = 0; i < kRows; i++)
        for (int j = 0; j < kCols; j++) {
            const Pitch& p = grid[i][j];
            if (!p.ok) continue;
            total++;
            if (p.fNat < lo) lo = p.fNat;
            if (p.fNat > hi) hi = p.fNat;
            if (p.jitter < 0.25f) coherent++;
        }
    if (total > 0)
        std::printf("\n  f_nat spans %.2f octaves; %d of %d oscillating points have jitter < 0.25\n",
                    std::log2(hi / lo), coherent, total);
    return 0;
}
