#!/usr/bin/env python3
"""
export_fallback.py — the compiled-in fallback capture, from a CC-licensed starter capture.

With no card, or a card that will not read, the firmware plays one capture built into
the binary rather than going silent. Until 2026-10-02 that was the JCM800 from
nam/model_data_nam_a2.h — TONE3000 T3K-licensed, so it could be neither committed nor
shipped. David's suggestion: fall back to a starter capture instead. Those are CC0 or
CC-BY, so the header this writes is committed, and every build — release or not — has
a fallback it may redistribute.

Writes nam/fallback_capture.h from captures/starter/<file>.a2nb, checking the .a2nb's
CRC and that every weight survives the trip to text and back bit for bit.

    .venv/bin/python tools/export_fallback.py
"""

import pathlib
import struct
import sys
import zlib

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent
SRC = PROJECT / "captures" / "starter" / "n02_ORANGE_TH.a2nb"
OUT = PROJECT / "nam" / "fallback_capture.h"

CREDIT = {
    "title": "Orange TH100",
    "model": "031000ETH100Clean100WMV9",
    "creator": "tupalosa (https://www.tone3000.com/tupalosa)",
    "url": "https://www.tone3000.com/tones/orange-th100-6554",
    "licence": "CC BY, as declared on TONE3000 (checked 2026-10-02)",
}


def main():
    b = SRC.read_bytes()
    if b[:4] != b"A2NB":
        raise SystemExit(f"{SRC}: not an .a2nb")
    count = struct.unpack("<I", b[8:12])[0]
    gain = struct.unpack("<f", b[12:16])[0]
    name = b[16:28].split(b"\0")[0].decode()
    crc = struct.unpack("<I", b[28:32])[0]
    payload = b[32:]
    if count != 1871 or len(payload) != 4 * count or zlib.crc32(payload) & 0xFFFFFFFF != crc:
        raise SystemExit(f"{SRC}: header, length or CRC does not check out")
    w = np.frombuffer(payload, "<f4")

    # %.9g round-trips every float32 exactly; confirm rather than assume.
    text = [f"{float(x):.9g}f" for x in w]
    back = np.array([float(t[:-1]) for t in text], dtype=np.float32)
    if not np.array_equal(back.view(np.uint32), w.view(np.uint32)):
        raise SystemExit("weights do not round-trip through text")

    rows = [", ".join(text[i:i + 6]) for i in range(0, len(text), 6)]
    OUT.write_text(f"""// GENERATED by tools/export_fallback.py — do not edit by hand; rerun it.
//
// The fallback capture: compiled in, played when the card has no capture to load.
//
//   "{CREDIT['title']}" ({CREDIT['model']}) by {CREDIT['creator']}
//   {CREDIT['url']}
//   Licence: {CREDIT['licence']}.
//   Changes: the A2-Lite network extracted from the .nam download and stored here as
//   a C array; output gain {gain:.6g} set to match the starter set's level.
//
// Replaces the T3K-licensed JCM800 (2026-10-02), so this file is committed and every
// build may be redistributed.
#pragma once

namespace fallback
{{
inline constexpr const char* kName = "ORANGE*";  // the * marks the built-in one
inline constexpr float       kGain = {gain:.9g}f;
inline constexpr float kWeights[{count}] = {{
    """ + ",\n    ".join(rows) + """
};
} // namespace fallback
""")
    print(f"wrote {OUT.relative_to(PROJECT)}: {name}, {count} weights, gain {gain:.4g}, round-trip exact")


if __name__ == "__main__":
    main()
